@startuml
skinparam stateBackgroundColor #E3F2FD
skinparam stateBorderColor #1565C0

[*] --> PANEL_ADMINISTRACION

PANEL_ADMINISTRACION --> GESTION_USUARIOS : Accede
GESTION_USUARIOS --> PANEL_ADMINISTRACION : Vuelve

GESTION_USUARIOS --> EDITANDO_USUARIO : Modifica
EDITANDO_USUARIO --> GESTION_USUARIOS : Guarda

PANEL_ADMINISTRACION --> GESTION_ASIGNATURAS : Accede
GESTION_ASIGNATURAS --> PANEL_ADMINISTRACION : Vuelve

GESTION_ASIGNATURAS --> EDITANDO_ASIGNATURA : Modifica
EDITANDO_ASIGNATURA --> GESTION_ASIGNATURAS : Guarda

@enduml