@startuml CU-22_BuscarEscenario
skinparam {
    NoteBackgroundColor #whiteSmoke
    ArrowColor #green
    NoteBorderColor #black
    linetype polyline
}

skinparam state {
    BackgroundColor #whiteSmoke
}

hide empty description

state startState as "GESTION_ESCENARIOS"
state endState as "GESTION_ESCENARIOS"

startState -down-> BuscarEscenario

state BuscarEscenario {
    state IngresoTermino as " "
    state ValidarBusqueda <<choice>>
    state MostrarResultados as " "

    IngresoTermino --> ValidarBusqueda
    note on link
        <b>Profesor introduce</b>
        * Término de búsqueda
        * (título, área o estado)
    end note

    ValidarBusqueda -[#red]-> IngresoTermino
    note on link
        <b>Sistema muestra</b>
        * "No se encontraron resultados"
    end note

    ValidarBusqueda --> MostrarResultados
    note on link
        <b>Sistema muestra</b>
        * Lista filtrada de escenarios
    end note
}

BuscarEscenario -down-> endState

@enduml